-- Segments define named slices of contacts used as campaign enrollment input.
--
-- filter_criteria is a JSONB object — all keys are optional:
--   tags:         bigint[]  contacts whose tags array contains ALL specified tag IDs
--   status:       text      contacts.status exact match (e.g. "warm", "cold")
--   company_id:   bigint    contacts.company_id exact match
--   has_linkedin: boolean   true = linkedin_url IS NOT NULL, false = IS NULL
--
-- An empty {} criteria matches all contacts.

create table "public"."segments" (
    "id"               bigint generated by default as identity not null,
    "name"             text not null,
    "description"      text,
    "filter_criteria"  jsonb not null default '{}'::jsonb,
    "created_at"       timestamp with time zone not null default now(),
    "created_by"       bigint
);

alter table "public"."segments" enable row level security;

CREATE UNIQUE INDEX segments_pkey ON public.segments USING btree (id);

alter table "public"."segments"
    add constraint "segments_pkey" PRIMARY KEY using index "segments_pkey";

alter table "public"."segments"
    add constraint "segments_created_by_fkey"
    FOREIGN KEY (created_by) REFERENCES sales(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."segments" validate constraint "segments_created_by_fkey";

grant delete on table "public"."segments" to "authenticated";
grant insert on table "public"."segments" to "authenticated";
grant select on table "public"."segments" to "authenticated";
grant update on table "public"."segments" to "authenticated";

grant delete on table "public"."segments" to "service_role";
grant insert on table "public"."segments" to "service_role";
grant references on table "public"."segments" to "service_role";
grant select on table "public"."segments" to "service_role";
grant trigger on table "public"."segments" to "service_role";
grant truncate on table "public"."segments" to "service_role";
grant update on table "public"."segments" to "service_role";

create policy "Enable read access for authenticated users"
on "public"."segments"
as permissive for select to authenticated using (true);

create policy "Enable insert for authenticated users only"
on "public"."segments"
as permissive for insert to authenticated with check (true);

create policy "Enable update for authenticated users only"
on "public"."segments"
as permissive for update to authenticated using (true) with check (true);

create policy "Segments Delete Policy"
on "public"."segments"
as permissive for delete to authenticated using (true);

-- Returns the count of contacts matching a segment's filter_criteria.
-- Called by the UI for live preview counts without enrolling anyone.
CREATE OR REPLACE FUNCTION public.count_segment_contacts(criteria jsonb)
RETURNS bigint
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  result bigint;
BEGIN
  SELECT count(*) INTO result
  FROM contacts
  WHERE
    (criteria->>'status' IS NULL OR status = criteria->>'status')
    AND (criteria->'company_id' IS NULL OR company_id = (criteria->>'company_id')::bigint)
    AND (
      criteria->'has_linkedin' IS NULL
      OR CASE WHEN (criteria->>'has_linkedin')::boolean
              THEN linkedin_url IS NOT NULL
              ELSE linkedin_url IS NULL
         END
    )
    AND (
      criteria->'tags' IS NULL
      OR jsonb_array_length(criteria->'tags') = 0
      OR tags @> ARRAY(SELECT jsonb_array_elements_text(criteria->'tags')::bigint)
    );
  RETURN result;
END;
$$;
