-- Campaign definitions and their email steps.
--
-- campaign_steps.html_body stores the inner body fragment only — the edge function
-- wraps it in the full email shell (greeting, signature, unsubscribe footer).
-- Use {first_name} in subject or html_body for interpolation.
--
-- delay_days: days after previous step's last_sent_at before this step is eligible.
-- Step 1 delay_days = 0 means send on first cron run after enrollment.

create table "public"."campaigns" (
    "id"          bigint generated by default as identity not null,
    "name"        text not null,
    "slug"        text not null,
    "description" text,
    "status"      text not null default 'draft',
    "created_at"  timestamp with time zone not null default now(),
    "created_by"  bigint
);

alter table "public"."campaigns" enable row level security;

CREATE UNIQUE INDEX campaigns_pkey ON public.campaigns USING btree (id);
CREATE UNIQUE INDEX campaigns_slug_key ON public.campaigns USING btree (slug);

alter table "public"."campaigns"
    add constraint "campaigns_pkey" PRIMARY KEY using index "campaigns_pkey";

alter table "public"."campaigns"
    add constraint "campaigns_slug_key" UNIQUE using index "campaigns_slug_key";

alter table "public"."campaigns"
    add constraint "campaigns_status_check"
    CHECK (status IN ('draft', 'active', 'paused', 'archived'));

alter table "public"."campaigns"
    add constraint "campaigns_created_by_fkey"
    FOREIGN KEY (created_by) REFERENCES sales(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."campaigns" validate constraint "campaigns_created_by_fkey";

create table "public"."campaign_steps" (
    "id"          bigint generated by default as identity not null,
    "campaign_id" bigint not null,
    "step_number" smallint not null,
    "subject"     text not null,
    "html_body"   text not null,
    "delay_days"  smallint not null default 0
);

alter table "public"."campaign_steps" enable row level security;

CREATE UNIQUE INDEX campaign_steps_pkey ON public.campaign_steps USING btree (id);
CREATE UNIQUE INDEX campaign_steps_campaign_step_key ON public.campaign_steps USING btree (campaign_id, step_number);

alter table "public"."campaign_steps"
    add constraint "campaign_steps_pkey" PRIMARY KEY using index "campaign_steps_pkey";

alter table "public"."campaign_steps"
    add constraint "campaign_steps_campaign_step_key"
    UNIQUE using index "campaign_steps_campaign_step_key";

alter table "public"."campaign_steps"
    add constraint "campaign_steps_campaign_id_fkey"
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."campaign_steps" validate constraint "campaign_steps_campaign_id_fkey";

grant delete on table "public"."campaigns" to "authenticated";
grant insert on table "public"."campaigns" to "authenticated";
grant select on table "public"."campaigns" to "authenticated";
grant update on table "public"."campaigns" to "authenticated";

grant delete on table "public"."campaigns" to "service_role";
grant insert on table "public"."campaigns" to "service_role";
grant references on table "public"."campaigns" to "service_role";
grant select on table "public"."campaigns" to "service_role";
grant trigger on table "public"."campaigns" to "service_role";
grant truncate on table "public"."campaigns" to "service_role";
grant update on table "public"."campaigns" to "service_role";

grant delete on table "public"."campaign_steps" to "authenticated";
grant insert on table "public"."campaign_steps" to "authenticated";
grant select on table "public"."campaign_steps" to "authenticated";
grant update on table "public"."campaign_steps" to "authenticated";

grant delete on table "public"."campaign_steps" to "service_role";
grant insert on table "public"."campaign_steps" to "service_role";
grant references on table "public"."campaign_steps" to "service_role";
grant select on table "public"."campaign_steps" to "service_role";
grant trigger on table "public"."campaign_steps" to "service_role";
grant truncate on table "public"."campaign_steps" to "service_role";
grant update on table "public"."campaign_steps" to "service_role";

create policy "Enable read access for authenticated users"
on "public"."campaigns"
as permissive for select to authenticated using (true);

create policy "Enable insert for authenticated users only"
on "public"."campaigns"
as permissive for insert to authenticated with check (true);

create policy "Enable update for authenticated users only"
on "public"."campaigns"
as permissive for update to authenticated using (true) with check (true);

create policy "Campaigns Delete Policy"
on "public"."campaigns"
as permissive for delete to authenticated using (true);

create policy "Enable read access for authenticated users"
on "public"."campaign_steps"
as permissive for select to authenticated using (true);

create policy "Enable insert for authenticated users only"
on "public"."campaign_steps"
as permissive for insert to authenticated with check (true);

create policy "Enable update for authenticated users only"
on "public"."campaign_steps"
as permissive for update to authenticated using (true) with check (true);

create policy "Campaign Steps Delete Policy"
on "public"."campaign_steps"
as permissive for delete to authenticated using (true);

-- Seed: formalise the existing 'outreach-2026' text campaign.
-- Body fragments use {first_name} interpolation; copy is placeholder pending final draft.

insert into "public"."campaigns" (id, name, slug, description, status)
overriding system value
values (1, 'Outreach 2026', 'outreach-2026', 'Initial outreach campaign', 'active');

insert into "public"."campaign_steps" (campaign_id, step_number, subject, html_body, delay_days) values
(
  1, 1,
  'Hi {first_name} — quick intro',
  '<p>I wanted to reach out and introduce myself briefly.</p>
<p>Would love to connect if the timing is right — happy to keep it short.</p>',
  0
),
(
  1, 2,
  'Following up, {first_name}',
  '<p>Just following up on my previous note in case it got buried.</p>
<p>Happy to jump on a quick call if that''s easier than email.</p>',
  3
),
(
  1, 3,
  'Last note, {first_name}',
  '<p>I''ll leave it here for now — just wanted to make sure my earlier notes didn''t get lost.</p>
<p>Feel free to reach out any time. The door''s always open.</p>',
  7
);

-- Advance sequence past seeded id
select setval('campaigns_id_seq', (select max(id) from campaigns));
