-- Drip campaign enrollment tracking.
-- Kept as a separate table from contacts to avoid polluting the core CRM schema
-- and to support future re-enrollment / multi-campaign scenarios.

create table "public"."drip_enrollments" (
    "id"                bigint generated by default as identity not null,
    "contact_id"        bigint not null,
    "campaign"          text not null,
    "step"              smallint not null default 0,
    "enrolled_at"       timestamp with time zone not null default now(),
    "last_sent_at"      timestamp with time zone,
    "completed_at"      timestamp with time zone,
    "suppressed"        boolean not null default false,
    "suppressed_reason" text  -- 'bounce' | 'complaint'
);

alter table "public"."drip_enrollments" enable row level security;

CREATE UNIQUE INDEX drip_enrollments_pkey
    ON public.drip_enrollments USING btree (id);

-- Prevents double-enrollment in the same campaign.
-- Drop this constraint if re-enrollment is needed in the future.
CREATE UNIQUE INDEX drip_enrollments_contact_campaign_key
    ON public.drip_enrollments USING btree (contact_id, campaign);

alter table "public"."drip_enrollments"
    add constraint "drip_enrollments_pkey" PRIMARY KEY using index "drip_enrollments_pkey";

alter table "public"."drip_enrollments"
    add constraint "drip_enrollments_contact_campaign_key"
    UNIQUE using index "drip_enrollments_contact_campaign_key";

alter table "public"."drip_enrollments"
    add constraint "drip_enrollments_contact_id_fkey"
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."drip_enrollments" validate constraint "drip_enrollments_contact_id_fkey";

grant delete on table "public"."drip_enrollments" to "authenticated";
grant insert on table "public"."drip_enrollments" to "authenticated";
grant select on table "public"."drip_enrollments" to "authenticated";
grant update on table "public"."drip_enrollments" to "authenticated";

grant delete on table "public"."drip_enrollments" to "service_role";
grant insert on table "public"."drip_enrollments" to "service_role";
grant references on table "public"."drip_enrollments" to "service_role";
grant select on table "public"."drip_enrollments" to "service_role";
grant trigger on table "public"."drip_enrollments" to "service_role";
grant truncate on table "public"."drip_enrollments" to "service_role";
grant update on table "public"."drip_enrollments" to "service_role";

create policy "Enable read access for authenticated users"
on "public"."drip_enrollments"
as permissive for select to authenticated using (true);

create policy "Enable insert for authenticated users only"
on "public"."drip_enrollments"
as permissive for insert to authenticated with check (true);

create policy "Enable update for authenticated users only"
on "public"."drip_enrollments"
as permissive for update to authenticated using (true) with check (true);

create policy "Drip Enrollment Delete Policy"
on "public"."drip_enrollments"
as permissive for delete to authenticated using (true);
