-- Stores per-email delivery events from Resend webhooks.
-- One row per event per email — a single email can have multiple opens/clicks.
--
-- event_type values: delivered, opened, clicked, bounced, complained, unsubscribed
-- url is populated for email.clicked events only.
-- resend_email_id links back to the Resend email object if needed.

create table "public"."email_events" (
  "id"              bigint generated by default as identity not null,
  "enrollment_id"   bigint not null,
  "resend_email_id" text,
  "event_type"      text not null,
  "occurred_at"     timestamp with time zone not null default now(),
  "url"             text
);

alter table "public"."email_events" enable row level security;

CREATE UNIQUE INDEX email_events_pkey ON public.email_events USING btree (id);
CREATE INDEX email_events_enrollment_id_idx ON public.email_events (enrollment_id);

alter table "public"."email_events"
  add constraint "email_events_pkey" PRIMARY KEY using index "email_events_pkey";

alter table "public"."email_events"
  add constraint "email_events_enrollment_id_fkey"
  FOREIGN KEY (enrollment_id) REFERENCES drip_enrollments(id) ON DELETE CASCADE;

-- Authenticated users can read all events (for CRM UI)
grant select on table "public"."email_events" to "authenticated";
grant insert on table "public"."email_events" to "service_role";
grant select on table "public"."email_events" to "service_role";

create policy "Enable read for authenticated users"
on "public"."email_events"
as permissive for select to authenticated using (true);

-- Aggregate view: one row per enrollment with summary stats
-- Used by the enrollments panel to avoid N+1 queries.
CREATE OR REPLACE VIEW public.enrollment_event_summary AS
SELECT
  enrollment_id,
  count(*) filter (where event_type = 'delivered')    as delivered_count,
  count(*) filter (where event_type = 'opened')       as open_count,
  count(*) filter (where event_type = 'clicked')      as click_count,
  max(occurred_at) filter (where event_type = 'opened')  as last_opened_at,
  max(occurred_at) filter (where event_type = 'clicked') as last_clicked_at
FROM public.email_events
GROUP BY enrollment_id;

grant select on public.enrollment_event_summary to authenticated;
grant select on public.enrollment_event_summary to service_role;
